import 'package:flutter/material.dart';
import 'package:meal_app/models/category.dart';
import 'package:meal_app/models/meal.dart';

const DummyData =  [
  Category(
    id: "1",
    title: "Italian",
    color: Colors.purple,
  ),
  Category(
    id: "2",
    title: "Pakistani",
    color: Colors.yellow,
  ),
  Category(
    id: "3",
    title: "Afghani",
    color: Colors.green,
  ),
  Category(
    id: "4",
    title: "Indian",
    color: Colors.red,
  ),
  Category(
    id: "5",
    title: "Irani",
    color: Colors.pink,
  ),
  Category(
    id: "6",
    title: "Saudi",
    color: Colors.brown,
  ),
  Category(
    id: "7",
    title: "American",
    color: Colors.blue,
  ),
  Category(
    id: "8",
    title: "British",
    color: Colors.blueAccent,
  ),
  Category(
    id: "9",
    title: "Palistini",
    color: Colors.orangeAccent,
  ),
  Category(
    id: "10",
    title: "Australian",
    color: Colors.pinkAccent,
  ),

];
var mealsData = [
  Meal(
    id: 'm1',
    categories: ['c1', 'c2'],
    title: 'Spaghetti Carbonara',
    imageUrl: 'assets/images/spaghetti_carbonara.jpg', // Placeholder image URL
    ingredients: [
      '4 Eggs',
      '100g Pancetta',
      '350g Spaghetti',
      'Parmesan Cheese',
      'Black Pepper',
      'Salt',
    ],
    steps: [
      'Boil the water for the pasta',
      'Fry the pancetta with some oil',
      'Beat the eggs and add cheese and pepper',
      'Cook the pasta al dente',
      'Mix everything together',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutrnFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
Meal(
    id: 'm2',
    categories: ['c3', 'c4'],
    title: 'Chicken Alfredo Pasta',
    imageUrl: 'assets/images/chicken_alfredo_pasta.jpg',
    ingredients: [
      'Chicken Breast',
      '300g Fettuccine Pasta',
      '200ml Heavy Cream',
      'Garlic',
      'Butter',
      'Parmesan Cheese',
      'Salt',
      'Black Pepper',
    ],
    steps: [
      'Boil water for pasta, add salt',
      'Cook chicken until browned',
      'Cook pasta according to package instructions',
      'Saute garlic in butter, add heavy cream',
      'Add parmesan cheese, salt, and pepper, stir until smooth',
      'Combine pasta and sauce, serve hot',
    ],
    duration: 30,
    complexity: Complexity.Challenging,
    affordability: Affordability.Affordable,
    isGlutrnFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm3',
    categories: ['c2', 'c5'],
    title: 'Mushroom Risotto',
    imageUrl: 'assets/images/mushroom_risotto.jpg',
    ingredients: [
      'Arborio Rice',
      'Mushrooms',
      'Vegetable Broth',
      'White Wine',
      'Onion',
      'Garlic',
      'Butter',
      'Parmesan Cheese',
      'Olive Oil',
    ],
    steps: [
      'Saute onions and garlic in olive oil',
      'Add mushrooms, cook until tender',
      'Stir in arborio rice, cook until translucent',
      'Deglaze with white wine, stir continuously',
      'Gradually add vegetable broth, stirring constantly',
      'Stir in butter and parmesan cheese, serve hot',
    ],
    duration: 40,
    complexity: Complexity.Challenging,
    affordability: Affordability.luxuries,
    isGlutrnFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
   Meal(
    id: 'm4',
    categories: ['c1', 'c3'],
    title: 'Margherita Pizza',
    imageUrl: 'https://example.com/images/margherita_pizza.jpg',
    ingredients: [
      'Pizza Dough',
      'Tomato Sauce',
      'Fresh Mozzarella Cheese',
      'Fresh Basil Leaves',
      'Olive Oil',
      'Salt',
      'Black Pepper',
    ],
    steps: [
      'Preheat oven to 475°F (245°C)',
      'Stretch dough onto a pizza pan',
      'Spread tomato sauce evenly over dough',
      'Arrange mozzarella slices and basil leaves on top',
      'Drizzle with olive oil, season with salt and pepper',
      'Bake for 10-12 minutes until crust is golden brown',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutrnFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm5',
    categories: ['c2', 'c4'],
    title: 'Salmon Teriyaki',
    imageUrl: 'https://example.com/images/salmon_teriyaki.jpg',
    ingredients: [
      'Salmon Fillets',
      'Soy Sauce',
      'Brown Sugar',
      'Mirin',
      'Garlic',
      'Ginger',
      'Sesame Seeds',
      'Green Onions',
    ],
    steps: [
      'Mix soy sauce, brown sugar, mirin, garlic, and ginger in a bowl',
      'Marinate salmon in the sauce for 30 minutes',
      'Grill salmon over medium heat until cooked through',
      'Garnish with sesame seeds and green onions',
      'Serve hot with rice or vegetables',
    ],
    duration: 35,
    complexity: Complexity.Challenging,
    affordability: Affordability.Affordable,
    isGlutrnFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
];

